name: "fastapi-app-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: log
  scan_frequency: 1s
  enabled: true
  paths:
    - /app/logs/mlops-prod*
  fields:
    - service: fastapi-app #mlops-service
  fields_under_root: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "fastapi-app"